right:
  teleop:
    ros__parameters:
      enabled: true
      dt: 0.01
      home_position: &home_left [-0.3283, 0.6627, 0.0368, 1.3760, 1.7089, -0.7670]
      start_with_gripper_open: true
      gripper_enabled: true

      routines: '[
          {
            "type": "SetpointRoutine",
            "params":
            {
              "joint_positions": [-0.3283, 0.6627, 0.0368, 1.3760, 1.7089, -0.7670]
            }
          }
        ]'

left:
  teleop:
    ros__parameters:
      enabled: false

webrtc:
  ros__parameters:
    port: 9999
    local: false
    stream_cameras: false
    cameras:
      '{
        "video_left": 10,
        "video_right": 4
      }'