left:
  teleop:
    ros__parameters:
      enabled: true
      dt: 0.01
      home_position: &home_left [0.0291, -0.8330, 0.8161, -0.0383, 0.9695, 0.0414]
      start_with_gripper_open: false
      gripper_enabled: false

      routines: 
        '[
          {
            "type": "SetpointRoutine",
            "params": 
            {
              "joint_positions": [0.0291, -0.8330, 0.8161, -0.0383, 0.9695, 0.0414]
            }
          }
        ]'

right:
  teleop:
    ros__parameters:
      enabled: false

webrtc:
  ros__parameters:
    port: 9999
    local: false
    stream_cameras: true
    cameras:
      '{
        "video_left": 10,
        "video_right": 4
      }'